name: Deploy to Hostinger Agency Plan

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.HOSTINGER_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p ${{ secrets.HOSTINGER_SSH_PORT || '22' }} ${{ secrets.HOSTINGER_HOST }} >> ~/.ssh/known_hosts
        
    - name: Update version file
      run: |
        echo "deploy-$(date +%Y%m%d-%H%M%S) $(date -u +%Y-%m-%dT%H:%M:%SZ)" > version.txt
        
    - name: Update service worker cache
      run: |
        timestamp=$(date +%Y%m%d-%H%M%S)
        cache_version="cm-v$(date +%s)-$timestamp"
        sed -i "s/const CACHE_NAME = '[^']*'/const CACHE_NAME = '$cache_version'/" sw.js
        
    - name: Deploy to Hostinger
      run: |
        rsync -avz --delete \
          -e "ssh -p ${{ secrets.HOSTINGER_SSH_PORT || '22' }}" \
          --exclude='.git' \
          --exclude='.github' \
          --exclude='.gitignore' \
          --exclude='.vscode' \
          --exclude='.DS_Store' \
          --exclude='deploy.sh' \
          --exclude='deploy-config.json' \
          --exclude='deploy-quick.sh' \
          --exclude='test-deployment.sh' \
          --exclude='DEPLOYMENT_GUIDE.md' \
          --exclude='HOSTINGER_AGENCY_DEPLOYMENT.md' \
          --exclude='HOSTINGER_QUICK_REFERENCE.md' \
          --exclude='docs' \
          --exclude='*.md' \
          --exclude='node_modules' \
          --exclude='.env' \
          --exclude='backups' \
          --exclude='*.log' \
          --exclude='*.tmp' \
          ./ ${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_HOST }}:${{ secrets.HOSTINGER_PATH || 'public_html' }}/
          
    - name: Test deployment
      run: |
        sleep 10  # Wait for deployment to complete
        curl -f https://chicagosmoney.com/deploy-info.php || echo "Deployment test failed"
        
    - name: Notify deployment success
      run: |
        echo "✅ Deployment to Hostinger Agency Plan completed successfully!"
        echo "🌐 Site: https://chicagosmoney.com"
        echo "📊 Status: https://chicagosmoney.com/deploy-info.php"
